# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{levenshtein-ffi}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Balatero"]
  s.date = %q{2010-11-04}
  s.description = %q{Provides a fast, cross-Ruby implementation of the levenshtein distance algorithm.}
  s.email = %q{dbalatero@gmail.com}
  s.extensions = ["ext/levenshtein/extconf.rb"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "ext/levenshtein/.gitignore",
     "ext/levenshtein/extconf.rb",
     "ext/levenshtein/levenshtein.c",
     "ext/levenshtein/levenshtein.h",
     "levenshtein-ffi.gemspec",
     "lib/levenshtein.rb",
     "spec/levenshtein_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dbalatero/levenshtein-ffi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An FFI version of the levenshtein gem.}
  s.test_files = [
    "spec/levenshtein_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

